### ISSUE TITLE
Is available pretrained ARD student model?

### ISSUE THREAD

**Issue by LeeDoYup** [goldblum/AdversariallyRobustDistillation#1]
Could you release checkpoint of student model, which trained with ARD?

**Comment by goldblum** [comment]
Hi,

An ARD MobileNetV2 model can be found at the following link (which is also posted at the bottom of the home page of this repository):
https://drive.google.com/drive/folders/15Od-zi6HGwQoIym3AkLGzLVPaR8oH9UR?usp=sharing

Best Wishes,
Micah
