### ISSUE TITLE
Pretrained teacher model

### ISSUE THREAD

**Issue by jinnan-chen** [goldblum/AdversariallyRobustDistillation#3]
Hi, where could I find the for teacher pretrained model of resnet18 wrn and mobilenetv2? Thanks!

**Comment by goldblum** [comment]
Here's a Google Drive link containing adversarially trained WRN and ResNet-18 teacher models: https://drive.google.com/drive/folders/1h2pFKxO8Ip3vKjGxDjDZb769aDh6OFOv?usp=sharing

**Comment by jinnan-chen** [comment]
Actually, I mean the three teacher models without adversarial training which could achieve 0.94 acc on clean images. Thanks for your attention!

**Comment by goldblum** [comment]
I have now updated the google drive folder to contain clean trained WRN, ResNet-18 and MobileNetV2 on CIFAR-10.  Feel free to let me know if you have any other questions!

**Comment by mjmaher987** [comment]
> Here's a Google Drive link containing adversarially trained WRN and ResNet-18 teacher models: https://drive.google.com/drive/folders/1h2pFKxO8Ip3vKjGxDjDZb769aDh6OFOv?usp=sharing

it is not active
