### ISSUE TITLE
A question about your code

### ISSUE THREAD

**Issue by zhhiyuan** [goldblum/AdversariallyRobustDistillation#4]
I am a newbie in this field, and I have a question about your code. When you instantiate AttackPGD, you enter the initial model. During the training of the model, whether the weight of the model entered in PGD is not updated. 
Here is the detail about this issue. The following work did not update the parameters of basic_net.

```python 
net = AttackPGD(basic_net, config)
```

**Comment by goldblum** [comment]
Hi!  This code does update the parameters of basic_net since they are also parameters of net.
