### ISSUE TITLE
Missing keys in static_dict when loading pre-trained teacher model

### ISSUE THREAD

**Issue by Imane219** [goldblum/AdversariallyRobustDistillation#7]
When I tried to run your code with WRN_CIFAR10_adv.t7 you provided as the teacher model, I got a missing keys issue:
![image](https://user-images.githubusercontent.com/48405078/158010750-79e16894-58a4-48c6-8c68-90a1d19d43f4.png)
I am pretty sure that I chose the right net and set a valid path for teacher model when running.
Can you figure out why I can't load teacher model? Thanks a lot.

**Comment by goldblum** [comment]
Have you tried putting the model in DataParallel before you load the model weights?  Like after line 88 of main.py.

**Comment by Imane219** [comment]
> Have you tried putting the model in DataParallel before you load the model weights? Like after line 88 of main.py.

Thanks for replying. I didn't use DataParallel. Actually I use the same code as yours, except the parameter settings are different.

**Comment by goldblum** [comment]
You should try that.  I do not remember if that model was saved in DataParallel, and that is the most common cause of the error message you posted above.  Sorry, I did this project a very long time ago, and it was my first project, so I did not do a good job of making things reproducible!

**Comment by Imane219** [comment]
> You should try that. I do not remember if that model was saved in DataParallel, and that is the most common cause of the error message you posted above. Sorry, I did this project a very long time ago, and it was my first project, so I did not do a good job of making things reproducible!

Thank you! I will have a try.
