### ISSUE TITLE
Some questions about choosing a teacher model.

### ISSUE THREAD

**Issue by Imane219** [goldblum/AdversariallyRobustDistillation#8]
Hi, I noticed that your AT ResNet18 model achieves the accuracy of 76.54(benign), 44.46(robust).When I do adversarial training on RN18, I got a better accuracy of 84.06(benign), 49.35(robust). I used my AT teacher to train a MNV2 student, whose robust accuracy(47.74) is far less than your student(50.22). So I wonder how you choose the AT teacher model when applying the ARD method.
Thanks a lot.

**Comment by SongXY283** [comment]
Hi, may I ask about the pre-trained TRADES WideResNet (34-10) teacher model, where did you get it? It would be great if you can provide other pre-trained models. Thanks!

**Comment by goldblum** [comment]
We used the TRADES checkpoint from their repo.  This project was a very long time ago, so we haven't been storing any models except from the ARD model found in the Google Drive link.

**Comment by SongXY283** [comment]
Thank you!!!
